### ISSUE TITLE
Wrong function prototypes generated by Arduino IDE because of custom types in function arguments

### ISSUE THREAD

**Issue by ChrisCross3** [cirque-corp/Cirque_Pinnacle_1CA027#1]
I used your [example for 40mm trackpad with curved overlay](https://github.com/cirque-corp/Cirque_Pinnacle_1CA027/blob/master/Circular_Trackpad/TM040040/Example_Code/TM040040_SPI_CurvedOverlay/TM040040_SPI_CurvedOverlay.ino) code with the 40mm trackpad.
I had to manually add function declarations because Arduino IDE generated wrong prototypes due to its problems with custom types in function arguments.
After that it worked like a charm. Thanks for the code.

**Comment by PatrickSherwood** [comment]
Which version of the Arduino IDE are you working with? I haven't encountered this problem, but it will be good have the code work in as many versions as possible.

**Comment by cirque-jonb** [comment]
I've not seen this problem and I can't reproduce it with 1.8.13
