### ISSUE TITLE
Changes needed to make 40mm curved overly example work with 35mm trackpad and 23mm trackpad with flat overly

### ISSUE THREAD

**Issue by ChrisCross3** [cirque-corp/Cirque_Pinnacle_1CA027#2]
Which changes would be needed to make the 40mm curved overly example work with the 35mm trackpad and 23mm trackpad with flat overly?

In the specification documents the sensing resolution is the same, but I guess there is more to it since the 35mm trackpad seems to have some blind space when used with the 40mm code.

**Comment by PatrickSherwood** [comment]
The SPI_Demo and I2C_Demo projects are meant to work with flat overlays on circle sensors of any size. The TM040040_SPI_CurvedOverlay project is a special case.

**Comment by ChrisCross3** [comment]
Sorry, didn't recognized that.

Since the Dev Kit is coming with 40 and 35mm curved overlay trackpad, is it hard to port the code of the 40mm curved to use it with the 35mm curved?
The 23mm is only available with flat overlay anyway.

**Comment by cirque-jonb** [comment]
I think the 40mm code will work fine for the 35mm sensor (the curved overlays scale fairly well). It should work fairly well as is. If not, adjusting the hover table might be needed.
