### ISSUE TITLE
AnyMeas mode example has backward order of RAP_Write() parameters

### ISSUE THREAD

**Issue by 2bndy5** [cirque-corp/Cirque_Pinnacle_1CA027#7]
Correct me if I'm wrong, but the parameters passed to the `RAP_Write()` function are in reverse on [line 136 of the AnyMeas mode example](https://github.com/cirque-corp/Cirque_Pinnacle_1CA027/blob/6b4009a334eb6982eb7a2a5290a034b9460ac9ef/Additional_Examples/AnyMeas_Example/AnyMeas_Example.ino#L135-L136). The comment, just prior to this function call, says to disable X & Y tracking which is located in `HOSTREG__SYSCONFIG1` (address 0x03) register and asserted using the `HOSTREG__SYSCONFIG1__TRACK_DISABLE` bit mask (0x08). I noticed that the bit mask is used to pass the register address, and the register address is used to pass the register value which is backwards. I haven't tested the example as it is (trying to port the example to python), but all other parameters to `RAP_Write()` seem to be in the correct order. 

It would help more if Cirque actually published another Application Note about using AnyMeas mode as this example code is all I could find aside from bit 4 in register 0x03 described as "AnyMeas Enable" on page 40 of the [Specification Sheet](https://www.dropbox.com/s/to7pxwesph71666/IC-DS-150408%20Pinnacle%20Specification.pdf?dl=0#). For those that aren't well versed about the process of ADC muxing, the toggle & polarity polynomials are quite confusing in which a schematic about the ADC muxing circuit would be helpful and shed light on using the `ADCMUXCTRL_SENSENGATE`, `ADCMUXCTRL_SENSEP1GATE`, `ADCMUXCTRL_REF1GATE`, & `ADCMUXCTRL_REF0GATE` bit masks. For instance the Specification Sheet says on page 7 that "only one sense line is supported" while the comments in [Pinnacle.h](https://github.com/cirque-corp/Cirque_Pinnacle_1CA027/blob/6b4009a334eb6982eb7a2a5290a034b9460ac9ef/Additional_Examples/AnyMeas_Example/Pinnacle.h#L268-L276) say you can combine the bit masks to use both sense lines (I assume that would create a sort of deadband if it is actually supported).

**Comment by brianmonson** [comment]
@2bndy5 you are correct, this is a good find.  That is backwards on line 136, we'll fix it and re-commit the code.  
Also apologies for not having documentation on AnyMeas.  Honestly we've never had anyone use it without contacting us first.  Usually it is a customer that we've interfaced with and we assign them an FAE who answers their questions.  Thus the lack of exact documents.  
I can hopefully give you the info you're looking for and if you have more questions just get back on here and ask and I'll answer them.  

Toggle simply means enable the electrode to toggle or not.  With Pinnacle there is only one receive line so all 28 electrodes are outputs that will toggle with their excitation signal when enabled.

Polarity refers to the actual toggling polarity (positive or negative).  If there is too much positive or too much negative signal, the ADC will rail positive or negative.  So the polarity is required to get measurements within range.  If you toggle a number of electrodes and it is railed positive or negative you will want to work with the polarity settings to get the measurements within the ADC range. 

The sense mux does work.  There are two sense lines bonded out, sensen and sensep1.  So if you much them both in (ADCMUXCTRL_SENESEP1GATE|ADCMUXCTRL_SENSENGATE) both those pins will be active.  SenseP1 and SenseN are direct inversions of each other (ie SenseN is the negative, inverted version of SenseP1).  So there may be unique cases where you would want both, but the typical case is just using one or the other.  And there is no specific advantage of one or the other. 

The REF1 and REF0 items are caps inside the part that are used at production test.  Sometimes people want to mux those in for offset, but the cap values are so small (about .25pf) that typically they are not useful.  If you need offset capacitance, it is better done by using electrode polarity.

**Comment by 2bndy5** [comment]
Thank you so much. That does provide more info than I was able to surmise. I will try not to abuse your offer to answer more questions here, but it does seem inevitable (I may try contact info from spec sheet first).

**Comment by PatrickSherwood** [comment]
Hi Brendan,

The forum on our website is another great place to ask questions, or find answers to questions previously asked. That said, not many people have tackled the AnyMeas interface for Pinnacle, so I wouldn't expect to find many existing questions/answers pertaining to that.
